In [ ]:
# we can create own indexes
import pandas as pd
production=pd.Series([30,60,45,25],
                     index=["Rice","Wheat","Maize","Barley"])
print(production)

Rice      30
Wheat     60
Maize     45
Barley    25
dtype: int64

In [ ]:
#loc(location by label)
print(production["Rice"])
print(production.loc["Rice"])

30
30

In [ ]:
# Max ,Min , mean, sum,(idxmax(print the index label of max value))
print(production.sum())
print(production.max())
print(production.mean())
print(production.idxmax())

160
60
40.0
Wheat

In [ ]:
print(production.sum())
print(production.max())
print(production.mean())
print(production.idxmax())
print(production.idxmax(),"is having maximum value of ",production.max())

160
60
40.0
Wheat
Wheat is having maximum value of  60

In [ ]:
# Increase all production by 10%
increase_production=production*1.10
print(increase_production)

Rice      33.0
Wheat     66.0
Maize     49.5
Barley    27.5
dtype: float64

In [ ]:
# Production greater than 40%
high_production=production[production>40]
print(high_production)
print()
print(production>40)

Wheat    60
Maize    45
dtype: int64

Rice      False
Wheat      True
Maize      True
Barley    False
dtype: bool

In [ ]:
# Data Frame
import pandas as pd
df=pd.DataFrame({
    "name":["Akil","Bobby","Charan"],
    "age":[25,30,35],
     "city":["NY","LA","Chicago"]
    },index=["a","b","c"])
print(df)
print()
print(df.loc["b"])

     name  age     city
a    Akil   25       NY
b   Bobby   30       LA
c  Charan   35  Chicago

name    Bobby
age        30
city       LA
Name: b, dtype: object

In [ ]:
# When u want to remove some particular element
print(df)
print()
print(df.loc[["a","c"],["name","city"]])

     name  age     city
a    Akil   25       NY
b   Bobby   30       LA
c  Charan   35  Chicago

     name     city
a    Akil       NY
c  Charan  Chicago

In [ ]:
# loc (it includes last element)((we have to give  positions it doesnot takes integer)

print(df.loc["a":"c"])

     name  age     city
a    Akil   25       NY
b   Bobby   30       LA
c  Charan   35  Chicago

In [ ]:
# iloc (it doesnot includes last element)(we have to give integer it doest takes positions)
print(df.iloc[0:2])

    name  age city
a   Akil   25   NY
b  Bobby   30   LA

In [ ]:

print(df.iloc["a":"c"])

TypeError: cannot do positional indexing on Index with these indexers [a] of type str

In [8]:
import pandas as pd
# Fix: Added a third value to the 'age' list so all columns have 3 elements
df=pd.DataFrame({
    "name":["pinky","cuty","rinky"],
    "age":[36,23, 27,],
    "country":["UAE","USA","UK"]})

# Filter for age > 28
print(df.loc[df["age"]>28, ["name","age"]])

    name  age
0  pinky   36

In [9]:
print(df.iloc[[0,2],[0,2]])

    name country
0  pinky     UAE
2  rinky      UK

In [10]:
import pandas as pd
data={
    "farm":["farm A","farm B","farm C","farm D"],
    "crop":["wheat","rice","wheat","maize"],
    "area_hectare":[10,15,8,12],
    "production_tons":[30,60,24,36]
}
df=pd.DataFrame(data)
print(df)

     farm   crop  area_hectare  production_tons
0  farm A  wheat            10               30
1  farm B   rice            15               60
2  farm C  wheat             8               24
3  farm D  maize            12               36

In [11]:
# top 2 will arrises
df.head(2)

     farm   crop  area_hectare  production_tons
0  farm A  wheat            10               30
1  farm B   rice            15               60

In [12]:
# last 2 will comes
df.tail(2)

     farm   crop  area_hectare  production_tons
2  farm C  wheat             8               24
3  farm D  maize            12               36

In [13]:
# provides basic information about the data set
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   farm             4 non-null      object
 1   crop             4 non-null      object
 2   area_hectare     4 non-null      int64
 3   production_tons  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [14]:
# Basic summary in the form of statistics
df.describe()

       area_hectare  production_tons
count      4.000000         4.000000
mean      11.250000        37.500000
std        2.986079        15.779734
min        8.000000        24.000000
25%        9.500000        28.500000
50%       11.000000        33.000000
75%       12.750000        42.000000
max       15.000000        60.000000

In [15]:
# for the existing one want to add a new column to it
df["yield_tons_per_hectare"]=df["production_tons"]/df["area_hectare"]
print(df)

     farm   crop  area_hectare  production_tons  yield_tons_per_hectare
0  farm A  wheat            10               30                     3.0
1  farm B   rice            15               60                     4.0
2  farm C  wheat             8               24                     3.0
3  farm D  maize            12               36                     3.0

In [17]:
#display only farm
df.display(farm D),

SyntaxError: invalid syntax. Perhaps you forgot a comma? (ipython-input-3965486335.py, line 2)

In [23]:
# to display only farm B and farm D
df.iloc[[1,3]]

     farm   crop  area_hectare  production_tons  yield_tons_per_hectare
1  farm B   rice            15               60                     4.0
3  farm D  maize            12               36                     3.0

In [24]:
# first 3 columns only
df.iloc[[1,3],[0,1,2]]

     farm   crop  area_hectare
1  farm B   rice            15
3  farm D  maize            12

In [27]:
# iloc doesnot takes words(farm","crop","area_hectare) so use loc
df.loc[[1,3],["farm","crop","area_hectare"]]

     farm   crop  area_hectare
1  farm B   rice            15
3  farm D  maize            12

In [41]:
print(df["crop"]=="wheat")
print()
wheat_farms=df[df["crop"]=="wheat"]
print(wheat_farms)

0     True
1    False
2     True
3    False
Name: crop, dtype: bool

     farm   crop  area_hectare  production_tons  yield_tons_per_hectare
0  farm A  wheat            10               30                     3.0
2  farm C  wheat             8               24                     3.0

In [42]:
# Farms greater than 3
# Fixed typo: changed 'yield_ton_per_hectare' to 'yield_tons_per_hectare'
high_yield=df[df["yield_tons_per_hectare"]>3]
print(high_yield)

     farm  crop  area_hectare  production_tons  yield_tons_per_hectare
1  farm B  rice            15               60                     4.0

In [40]:
# sort the farms by highest production
sorted_df=df.sort_values(by="production_tons",ascending=False)
print(sorted_df)

     farm   crop  area_hectare  production_tons  yield_tons_per_hectare
1  farm B   rice            15               60                     4.0
3  farm D  maize            12               36                     3.0
0  farm A  wheat            10               30                     3.0
2  farm C  wheat             8               24                     3.0

In [46]:
# Restore the built-in print function by deleting the variable that overwrote it
del print

# Now retry printing the high_yield data
print(high_yield)

NameError: name 'print' is not defined

In [38]:
# Group by operation
avg_yield=df.groupby("crop")["yield_tons_per_hectare"].sum()
print(avg_yield)

crop
maize    3.0
rice     4.0
wheat    6.0
Name: yield_tons_per_hectare, dtype: float64